# Generated by Django 3.0.5 on 2020-05-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('Population', models.IntegerField(null=True)),
            ],
        ),
    ]
