# Generated by Django 3.0.5 on 2020-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateModelBasedOnYamlFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Postal', models.CharField(max_length=200)),
            ],
        ),
    ]
